# pretrain: /mnt/iMVR/sudhanshu/Projects/ActionCLIP/exp/clip_k400/ViT-B/16/mby140_fold2/fold2/model_best.pt
pretrain: /mnt/iMVR/sudhanshu/Projects/ActionCLIP/pretrained_mby140/clip_k400/ViT-B/16/mby140_fold0/fold0/model_best.pt
seed: 1024
data:
    dataset: mby140
    modality: RGB
    num_segments: 8
    seg_length: 1
    split: 1
    batch_size: 16
    workers: 16
    gpus: 4
    num_classes: 3
    image_tmpl: 'img_{:08d}.jpg'
    val_list: 'lists/mby140/fold0/mb_test.txt' #
    label_list: 'lists/mby140_labels.csv'
    index_bias: 1
    input_size: 224
    random_shift: False
network:
    arch: ViT-B/16  #ViT-B/32 ViT-B/16
    init: True
    tsm: False
    drop_out: 0.0 
    emb_dropout: 0.0 
    bn_momentum: 0.1
    consensus_type: avg
    type: clip_k400
    sim_header: "Transf"   #Transf   meanP  LSTM  Conv_1D  Transf_cls
    joint: False
    describe:
    ratio: 1
    f_ratio: 10
logging:
    print_freq: 10
    eval_freq: 1
